config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  resources :bloods ,except: [:index, :destroy]

  devise_for :donors, controllers: {registrations: "donors/registrations", sessions: "donors/sessions", confirmations: "donors/confirmations", passwords: "donors/passwords"}
  devise_for :banks, controllers: {registrations: "banks/registrations", sessions: "banks/sessions", confirmations: "banks/confirmations", passwords: "banks/passwords"}
  devise_for :hospitals, controllers: {registrations: "hospitals/registrations", sessions: "hospitals/sessions", confirmations: "hospitals/confirmations", passwords: "hospitals/passwords"}

  root 'general#home'
  get  "/donor/dashboard" => "general#donor_dashboard" , as: "donor_dashboard"
  get  "/bank/dashboard" => "general#bank_dashboard" , as: "bank_dashboard"
  get "/bank/requests" => "general#requests", as: "requests"
  get  "/hospital/dashboard" => "general#hospital_dashboard" , as: "hospital_dashboard"
  post "/bank/accept_request/:request_id" => "general#accept_request", as: "accept_request"
  post "/bank/reject_request/:request_id" => "general#reject_request", as: "reject_request" 

end

app/controllers/general_controller.rb
class GeneralController < ApplicationController
  
  def home
    
  end

  def donor_dashboard
  	@donations = current_donor.bloods.reverse
  end

  def bank_dashboard
  	@donations = current_bank.bloods.reverse
  end

  def requests
    @requests = current_bank.orders.reverse
  end

  def hospital_dashboard
  	@orders = current_hospital.orders.reverse
  end

  def accept_request
    request = Order.find(params[:request_id])
    request.granted!
    redirect_to requests_path
  end

  def reject_request
    request = Order.find(params[:request_id])
    request.rejected!
    redirect_to requests_path
  end

end

app/helpers/general_helper.rb
module GeneralHelper
end

app/views/general/bank_dashboard.html.erb
<%= link_to "View Blood Requests", requests_path, class: "btn-large"%>
<%= link_to "Log Out", destroy_bank_session_path, method: "delete", class: "btn-large right"%>
<div class="table-box white card hoverable z-depth-4"><p class="table_head">Received Blood Donations</p>
  <table class="responsive-table striped">
    <thead>
        <tr>
            <th>Blood Type</th>
            <th>Donor Name</th>
            <th>Volume(in ml)</th>
            <th>Date</th> 
        </tr>
    </thead>

    <tbody>
      <% @donations.each do |donation| %>
        <tr>
          <td><%= donation.category %></td>
          <td><%= donation.donor.full_name %></td>
          <td><%= donation.amount %></td>
          <td><%= donation.created_at%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/general/donor_dashboard.html.erb
<a href="/bloods/new" class="btn-large">Donate Now</a>
<%= link_to "Log Out", destroy_donor_session_path, method: "delete", class: "btn-large right"%>
<div class="table-box white card hoverable z-depth-4"><p class="table_head">Blood Donations</p>
  <table class="responsive-table striped">
    <thead>
        <tr>
            <th>Blood Type</th>
            <th>Blood Bank Name</th>
            <th>Volume(in ml)</th>
            <th>Date</th> 
        </tr>
    </thead>

    <tbody>
      <% @donations.each do |donation| %>
        <tr>
          <td><%= donation.category %></td>
          <td><%= donation.bank.name %></td>
          <td><%= donation.amount %></td>
          <td><%= donation.created_at%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/general/home.html.erb
<div class="row section center container white form hoverable z-depth-5">

<%= link_to "Donor Section", new_donor_session_path, class: "btn-large row z-depth-2" %> <br/>
<%= link_to "Blood Bank Section", new_bank_session_path, class: "btn-large row z-depth-2" %> <br/>
<%= link_to "Hospital Section", new_hospital_session_path, class: "btn-large row z-depth-2" %> <br/>

</div>

app/views/general/hospital_dashboard.html.erb
<%= link_to "New Blood Order", new_order_path, class: "btn-large"%>
<%= link_to "Log Out", destroy_hospital_session_path, method: "delete", class: "btn-large right"%>

<div class="table-box white card hoverable z-depth-4"><p class="table_head">Blood Orders</p>
  <table class="responsive-table striped">
    <thead>
        <tr>
            <th>Blood Type</th>
            <th>Blood Bank Name</th>
            <th>Volume(in ml)</th>
            <th>Date</th> 
            <th>Status</th>
        </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%=order.blood_type%></td>
          <td><%= order.bank.name %></td>
          <td><%= order.amount %></td>
          <td><%= order.created_at%></td>
          <td><%= order.status%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/general/requests.html.erb
<%= link_to "View Dashboard", bank_dashboard_path, class: "btn-large"%>
<%= link_to "Log Out", destroy_bank_session_path, method: "delete", class: "btn-large right"%>
<div class="table-box white card hoverable z-depth-4"><p class="table_head">Received Blood Requests</p>
  <table class="responsive-table striped">
    <thead>
        <tr>
            <th>Blood Type</th>
            <th>Hospital Name</th>
            <th>Volume(in ml)</th>
            <th>Date</th> 
            <th>Action</th> 
        </tr>
    </thead>

    <tbody>
      <% @requests.each do |request| %>
        <tr>
          <td><%= request.blood_type%></td>
          <td><%= request.bank.name %></td>
          <td><%= request.amount %></td>
          <td><%= request.created_at%></td>
          <% if request.pending? %>
            <td><%= link_to "Accept", accept_request_path(request.id), method: "post", class: "btn" %> <%= link_to "Reject", reject_request_path(request.id), method: "post", class: "btn" %></td>
          <% else %>
            <td><%= request.status%></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>