config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  resources :bloods ,except: [:index, :destroy]

  devise_for :donors, controllers: {registrations: "donors/registrations", sessions: "donors/sessions", confirmations: "donors/confirmations", passwords: "donors/passwords"}
  devise_for :banks, controllers: {registrations: "banks/registrations", sessions: "banks/sessions", confirmations: "banks/confirmations", passwords: "banks/passwords"}
  devise_for :hospitals, controllers: {registrations: "hospitals/registrations", sessions: "hospitals/sessions", confirmations: "hospitals/confirmations", passwords: "hospitals/passwords"}

  root 'general#home'
  get  "/donor/dashboard" => "general#donor_dashboard" , as: "donor_dashboard"
  get  "/bank/dashboard" => "general#bank_dashboard" , as: "bank_dashboard"
  get "/bank/requests" => "general#requests", as: "requests"
  get  "/hospital/dashboard" => "general#hospital_dashboard" , as: "hospital_dashboard"
  post "/bank/accept_request/:request_id" => "general#accept_request", as: "accept_request"
  post "/bank/reject_request/:request_id" => "general#reject_request", as: "reject_request" 

end

app/models/blood.rb
class Blood < ActiveRecord::Base
	belongs_to :donor
	belongs_to :bank
end

app/controllers/bloods_controller.rb
# class DonationsController < ApplicationController
#   before_action :set_blood, only: [:edit]
#   def new
#   	@blood = Blood.new
#   end

#   def create
#   	@blood = Blood.new(blood_params)
#   	@blood.donor = current_donor
#   	@blood.bank = Bank.find(params[:blood][:bank_id])
#   	@blood.save
#   	redirect_to donor_dashboard_path
#   end

#   def edit
#   	@blood = Blood.update(blood_params)
#   end

#   private
  
#   def set_blood
#   	@blood = Blood.find(params[:blood])
#   end

#   def blood_params
#   	params.require(:blood).permit(:type, :amount)
#   end

# end

class BloodsController < ApplicationController
  
  before_action :set_blood , only: [:show, :edit, :update]
  before_action :authenticate_donor! , only: [:new, :edit, :create, :update]
  before_action :check_authority , only: [:update, :edit]

  def new
    @blood = Blood.new
  end

  def edit
  end

  def create
    @blood = Blood.new(blood_params)
    @blood.donor = current_donor
    @blood.bank = Bank.find(params[:blood][:bank_id])
    respond_to do |format|
      if @blood.save
        format.html { redirect_to donor_dashboard_path, notice: 'Donation was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
  	@blood.bank = Bank.find(params[:blood][:bank_id])
    respond_to do |format|
      if @blood.update(blood_params)
        format.html { redirect_to @blood, notice: 'Donation was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blood
      @blood = Blood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blood_params
 		 	params.require(:blood).permit(:category, :amount)
    end

    def check_authority
      if current_donor == @blood.donor
        true
      else
        redirect_to donor_dashboard_path , alert: "Unauthorized to make any change"
        return
      end
    end
    
end

app/views/bloods/_form.html.erb
<div class="row white container form hoverable z-depth-5">
  <p class="form_heading">Blood Donation Details</p>

<%= form_for(@blood, class: "col s12") do |f| %>
  
  <div class="row">
    <% if @blood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blood.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @blood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <div class="input-field col s6">
      <%= f.select :category,["A+", "A-","B+","B-","AB+","AB-","O+","O-"], required: true, default:"A+" %>
    </div>
    <div class="input-field col s6">
      <%= f.label "Blood volume (in ml) " %>
      <%= f.number_field :amount, required: true %>
    </div>

    <div class="input-field col s6">
      <%= f.select :bank_id, options_for_select(Bank.all.collect{ |u| [u.name, u.id] }), required: true %>
    </div>

    <div class="input-field col s12"> 
      <%= f.submit "Submit", class: "btn" %>
    </div>

  </div>

<% end %>

app/views/bloods/edit.html.erb
<%= render "form" %>

app/views/bloods/new.html.erb
<%= render 'form' %>

app/views/bloods/show.html.erb
<p id="notice"></p>

<p>
  <strong>Type:</strong>
  <%= @blood.category %>
</p>

<p>
  <strong>Amount:</strong><br/>
  <%= @blood.amount %>ml<br/>
</p>

<p>
  <strong>Blood Bank:</strong>
  <%= @blood.bank.name %>
</p>

<%= link_to 'Edit', edit_blood_path(@blood) %>