config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  resources :bloods ,except: [:index, :destroy]

  devise_for :donors, controllers: {registrations: "donors/registrations", sessions: "donors/sessions", confirmations: "donors/confirmations", passwords: "donors/passwords"}
  devise_for :banks, controllers: {registrations: "banks/registrations", sessions: "banks/sessions", confirmations: "banks/confirmations", passwords: "banks/passwords"}
  devise_for :hospitals, controllers: {registrations: "hospitals/registrations", sessions: "hospitals/sessions", confirmations: "hospitals/confirmations", passwords: "hospitals/passwords"}

  root 'general#home'
  get  "/donor/dashboard" => "general#donor_dashboard" , as: "donor_dashboard"
  get  "/bank/dashboard" => "general#bank_dashboard" , as: "bank_dashboard"
  get "/bank/requests" => "general#requests", as: "requests"
  get  "/hospital/dashboard" => "general#hospital_dashboard" , as: "hospital_dashboard"
  post "/bank/accept_request/:request_id" => "general#accept_request", as: "accept_request"
  post "/bank/reject_request/:request_id" => "general#reject_request", as: "reject_request" 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BloodBank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>
<ul id="dropdown1" class="dropdown-content">
  <% if current_donor.nil? %>
  	<li><%= link_to "Sign in as Donor", new_donor_session_path%></li>
  <% else %>
  	<li><%= link_to "Sign Out Donor", destroy_donor_session_path, method: "delete"%></li>
  <% end %>
  
  <% if current_hospital.nil? %>
  	<li><%= link_to "Sign in as Hospital", new_hospital_session_path%></li>
  <% else %>
  	<li><%= link_to "Sign Out Hospital", destroy_hospital_session_path, method: "delete"%></li>
  <% end %>

	<% if current_bank.nil? %>
  	<li><%= link_to "Sign in as Blood Bank", new_bank_session_path%></li>
  <% else %>
  	<li><%= link_to "Sign Out Blood Bank", destroy_bank_session_path, method: "delete"%></li>
  <% end %>

</ul>
<nav>
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">Blood Bank Management System</a>
    <ul class="right hide-on-small-only">
      <li><%= link_to "Home", root_path %></li>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>